name: "Post to Bluesky"

on:
  workflow_dispatch:
  schedule:
    - cron: "7,22,37,52 * * * *"

concurrency:
  group: welsh-fairy-bot-scheduler
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - name: Check schedule and possibly post
        run: npm run schedule
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          SCHEDULER_GITHUB_TOKEN: ${{ secrets.SCHEDULER_GITHUB_TOKEN }}
          MIN_POST_INTERVAL_MINUTES: ${{ vars.MIN_POST_INTERVAL_MINUTES }}
          MAX_POST_INTERVAL_MINUTES: ${{ vars.MAX_POST_INTERVAL_MINUTES }}
